trigger:
- master

pool:
  vmImage: 'ubuntu 16.04'
#variables:

steps:
- task: GitVersion@5
  name: gitversion
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'

# - task: PowerShell@2
#   inputs:
#     targetType: 'inline'
#     script: |
#       $Env:ModuleVersion = $(GitVersion.)

- task: PowerShell@2
  inputs:
    filePath: './build.ps1'
    arguments: '-ResolveDependency'
    pwsh: true
  env:
    ModuleVersion: $(GitVersion.SemVer)
