trigger:
- master

pool:
<<<<<<< HEAD
  vmImage: 'ubuntu 16.04'
#variables:
=======
  name: Default

variables:
>>>>>>> fixing AZDO yml structure

steps:
- task: GitVersion@5
  name: gitversion
  inputs:
    runtime: 'core'
    configFilePath: 'GitVersion.yml'

- task: PowerShell@2
  inputs:
    filePath: './build.ps1'
    arguments: '-ResolveDependency'
    pwsh: true
  env:
    ModuleVersion: $(GitVersion.Informationalversion)
